### ISSUE TITLE
define DESI_PRODUCT_ROOT

### ISSUE THREAD

**Issue by sbailey** [desihub/desitree#2]
It seems that "module load desitree" should define $DESI_PRODUCT_ROOT, but it does not.  I see an old svn commit entry that specifically disabled this:

https://desi.lbl.gov/trac/changeset/837/code

But why?  I was expecting this to be set when I tried running "desiInstall" and it complained that $DESI_PRODUCT_ROOT wasn't set.

**Comment by weaverba137** [comment]
That's because DESI_PRODUCT_ROOT is only meant to be defined on non-NERSC systems.  On NERSC systems, /project/projectdirs/desi/software/$NERSC_HOST is automatically detected.

What _specific_ package is requiring the existence of $DESI_PRODUCT_ROOT?  Remember, we are no longer supporting Modules on non-NERSC systems, and since desitree is literally _only_ a Module file, I guess this issue must be related to a NERSC install.  But again, the NERSC specific case is already handled in every product that follows the template.  So I'm puzzled by this request.

**Comment by weaverba137** [comment]
PS, the message I think you saw from desiInstall is only a warning, and can safely be ignored on NERSC systems.  This message will probably be disabled in a future release of desiutil.

**Comment by weaverba137** [comment]
I'm going to assume that this question has been answered.
